name = "Cube Drop Test"
author = "doksok"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a8d6deb1b38bd41b6102a9bb1b7b0876a647b0faeca02d578108dca13164c4b"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
