name = "Cube Drop Test"
author = "doksok"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3dc1bf0ed8fb4f7191cae96e78a88e5ede5a09ecfdddd99bd47164bf432e08fa"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
