name = "Cube Drop Test"
author = "doksok"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee3dad500e7c3eb342b736ca115a1421b2e9e33faf32760ba402dc58053529ea"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
